config/routes.rb
Rails.application.routes.draw do
  root 'groups#index'
  devise_for :users
  resources :groups, except: [:destroy, :show] do
    resources :messages, only: [:index, :create]
    collection do
      get 'search'
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/group.rb
class Group < ApplicationRecord
  has_many :messages
  has_many :group_users, dependent: :destroy
  has_many :users, through: :group_users
  accepts_nested_attributes_for :group_users, allow_destroy: true

  validates :name, presence: true
end

app/models/group_user.rb
class GroupUser < ApplicationRecord
  belongs_to :group
  belongs_to :user
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :user
  belongs_to :group

  validates :body, presence: true

  mount_uploader :image, ImageUploader
end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :messages
  has_many :group_users, dependent: :destroy
  has_many :groups, through: :group_users
end

app/controllers/application_controller.rb
private
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  def after_sign_in_path_for(resource)
    root_path
  end

  def after_sign_out_path_for(resource)
    new_user_session_path
  end

  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
    devise_parameter_sanitizer.permit(:account_update, keys: [:name])
  end
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_action :authenticate_user!
  before_action :find_group_params, only: [:edit, :update]

  def index
    @groups = current_user.groups.order(id: :DESC)
  end

  def new
    @group = Group.new
  end

  def create
    @group = Group.new(group_params)
    if @group.save
      respond_to do |format|
        format.html { redirect_to root_path, notice: "グループを作成しました" }
        format.json
      end
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @group.update(group_params)
      redirect_to group_messages_path(@group), notice: "グループを編集しました"
    else
      render :edit
    end
  end

  def search
    @users_except_me = User.where.not(id: current_user.id)
    @users = @users_except_me.where('name LIKE(?)', "%#{params[:name]}%")
    render json: @users
  end

  private

  def group_params
    user_ids = params[:group]["user_ids"]
    user_ids << current_user.id.to_s
    params.require(:group).permit(:name, user_ids: [])
  end

  def find_group_params
    @group = Group.find(params[:id])
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  before_action :authenticate_user!
  before_action :index_variables, only: [:index, :create]

  def index
    if @users.ids.include?(current_user.id)
      @message = Message.new
      respond_to do |format|
        format.html
        format.json
      end
    else
      flash.now[:alert] = "このグループの参加者ではありません"
      redirect_to root_path
    end
  end

  def create
    @message = current_user.messages.new(message_params)
    if @message.save
      respond_to do |format|
        format.json
      end
    else
      flash.now[:alert] = "メッセージを入力してください"
      render :index
    end
  end

  private

  def message_params
    params.require(:message).permit(:body, :image).merge(group_id: params[:group_id])
  end

  def index_variables
    @groups = current_user.groups.order(created_at: :DESC)
    @group = Group.find(params[:group_id])
    @users = @group.users
    @messages = @group.messages.order(created_at: :DESC).includes(:user)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/groups/_content-left.haml
.content-left
  .user
    = link_to root_path do
      %p.user__name
        = current_user.name
    = link_to new_group_path do
      %i.fa.fa-edit
    = link_to edit_user_registration_path do
      %i.fa.fa-cog

  .group-wrapper
    = render partial: 'groups/group-list', collection: @groups, as: :group

app/views/groups/_group-form.haml
- if @group.errors.any?
  .chat-group-form__errors
    %ul
      %h2
        = "#{@group.errors.count}件のエラーがあります"
      -@group.errors.full_messages.each do |message|
        %li
          = message

= form_for @group do |f|
  .chat-group-form__field.clearfix
    .chat-group-form__field--left
      .chat-group-form__label
        = f.label :name, 'グループ名'
    .chat-group-form__field--right
      = f.text_field :name, class: 'chat-group-form__input', id: 'chat_group_name', placeholder: 'グループ名を入力してください'

  .chat-group-form__field.clearfix
    .chat-group-form__field--left
      .chat-group-form__label
        = f.label :users, 'チャットメンバーの追加'
    .chat-group-form__field--right
      %input#user-search-field{ class: "chat-group-form__input",placeholder: "検索するユーザー名を入力してください", autocomplete: "off" }
      #user-search-result

  .chat-group-form__field.clearfix
    .chat-group-form__field--left
      %label.chat-group-form__label{for: "chat_group_チャットメンバー"} チャットメンバー
    .chat-group-form__field--right
      #chat-group-users
        .chat-group-user.clearfix
          %p.chat-group-user__name
            = current_user.name
        - @group.users.each do |user|
          - if user != current_user
            .chat-group-user.clearfix{ id: "chat-group-user-#{user.id}" }
              %input{ type: "hidden", name: "group[user_ids][]", value: user.id }
              %p.chat-group-user__name
                = user.name
              - if user.id != current_user.id
                %a.user-search-remove.chat-group-user__btn.chat-group-user__btn--remove{ 'data-user-id': user.id }削除

  .chat-group-form__field.clearfix
    .chat-group-form__field--left
    .chat-group-form__field--right
      = f.submit class: "chat-group-form__action-btn", type: "submit", value: "Save"

app/views/groups/_group-list.haml
= link_to group_messages_path(group) do
  .groups
    %p.groups__name
      = group.name
    %p.groups__message
      - if group.messages.present?
        = group.messages.last.body

app/views/groups/edit.html.haml
.chat-group-form
  %h1 チャットグループ編集
  = render 'group-form'

app/views/groups/index.haml
= render 'content-left'

.content-right
  .group
    %p.group__name グループを選択してください
    %p.group__member MEMBER:

  .bottom-content
    .submit
      %input{ class: "submit__content", placeholder: 'グループを選択してください'}
    %i.fa.fa-file-image-o
    %p.submit__btn Send

app/views/groups/new.html.haml
.chat-group-form

  %h1 新規チャットグループ
  = render 'group-form'

app/views/layouts/_flash.html.haml
- flash.each do |key, value|
  = content_tag(:div, value, class: "flash flash__#{key}")

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title ChatSpace
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  %body
  = render 'layouts/flash'
  = yield

app/views/messages/_chat.haml
.chat{ "data-message-id": "#{message.id}"}
  %p.chat__user
    = message.user.name
  %p.chat__date
    = message.created_at.strftime("%Y年%m月%d日 %H時%M分")
  %p.chat__content
    = message.body
  %p.chat__image
    - if message.image.present?
      = image_tag(message.image)

app/views/messages/index.html.haml
= render 'groups/content-left'

.content-right
  .group
    %p.group__name
      = @group.name
    %p.group__member
      MEMBER:
      = @users.pluck(:name).join(",")

    = link_to edit_group_path(@group) do
      %p.group__btn Edit

  .chat-wrapper
    = render partial: 'chat', collection: @messages, as: :message

  .bottom-content
    .submit
    = form_for [@group, @message], html: { class: "form js-message" } do |f|
      = f.text_field :body, class: "submit__content js-form__text-field", placeholder: 'type a message'
      %label.chat-footer__file
        = f.file_field :image
        %i.fa.fa-file-image-o
      = f.submit "Send", class: "submit__btn", name: "Commit"